### ISSUE TITLE
problem compiling against 2.8.x

### ISSUE THREAD

**Issue by gour** [martin-pe/maitreya8#1] opened 2016-12-29 10:42 UTC
The same problem #8 (https://github.com/martin-pe/maitreya7/issues/8) which I have with maitreya7 is present with maitreya8 as well.

**Comment by martin-pe** [comment] 2017-01-06 06:11
Seems to be a general problem with the wxGTK (GTK3) implementation on Fedora.
I reproduced the problem with a standard wx sample as follows.
Download and unpack the wx 3.0.2 distro, go to samples/toolbar, type "make -f makefile.unx". Start the program "toolbar".
You can see that toolbar and menu are missing.  You can activate the menu with e.g. "Alt+F", but the menu bar is still not visible.
Do you want to report that bug to the wxWidgets or Fedora list?
I do not use wxWidgets with GTK3 at all because there are several other issues. Unfortunately this is still bleeding edge - years after the first appearance of GTK3.
I did not compile the wx distro with GTK2 (default) option on Fedora, but quite sure that is will be okay.
![screenshot](https://cloud.githubusercontent.com/assets/13454741/21709171/3417ddb8-d3df-11e6-9bf6-f7407630e88c.png)

**Comment by gour** [comment] 2017-01-08 08:01
The updated package (now available in testing repository) solves the problem. :-)

**Comment by martin-pe** [comment] 2017-01-08 09:06
great, so I close the issue

**Closed by martin-pe** 2017-01-08 09:06 UTC
